package com.proyectS1.warehouse_management.dtos.response;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

import com.proyectS1.warehouse_management.model.enums.ReportType;

import io.swagger.v3.oas.annotations.media.Schema;

public record ReportPreviewResponseDTO(
    @Schema(description = "Report type")
    ReportType reportType,
    @Schema(description = "Report title")
    String title,
    @Schema(description = "Report subtitle")
    String subtitle,
    @Schema(description = "Report description")
    String description,
    @Schema(description = "Generation date")
    LocalDateTime generatedAt,
    @Schema(description = "Generated by")
    String generatedBy,
    @Schema(description = "Applied filters")
    Map<String, String> filters,
    @Schema(description = "Summary KPIs")
    List<ReportSummaryItemDTO> summary,
    @Schema(description = "Report columns")
    List<ReportColumnDTO> columns,
    @Schema(description = "Report rows")
    List<Map<String, String>> rows
) {
}
